---
image: bradrydzewski/python:2.7

services:
  - mongodb

script:
  - sudo apt-get update > /dev/null
  - "sudo DEBIAN_FRONTEND='noninteractive' apt-get install -y libsasl2-dev libssl-dev rsyslog > /dev/null"
  - sudo /usr/sbin/rsyslogd > /dev/null
  - pip install -r requirements.txt > /dev/null
  - pip install nose coverage flake8 mock funcsigs > /dev/null
  - flake8 .
  - cp anchor/config/config.example.py anchor/config/config.py
  - cp anchor/config/celery-example.py anchor/config/celery.py
  - nosetests -v --cover-erase --with-coverage --cover-package=anchor
