sudo: false
language: python
python:
  - 2.6
  - 2.7
services:
  - mongodb
install:
  - pip install -r requirements.txt
before_script:
  - cp anchor/config/config.example.py anchor/config/config.py
  - cp anchor/config/celery-example.py anchor/config/celery.py
script: nosetests
